version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - run:
        command: npm run test
        name: Run tests
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
    # Specify the version you desire here
    # See: https://circleci.com/developer/images/image/cimg/base
    - image: cimg/base:current

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
    # Checkout the code as the first step.
    - checkout
    - run:
        name: "Say hello"
        command: "echo Hello, World!"
workflows:
  test_my_app:
    jobs:
    - test
    filters:
      branches:
        only: main # only deploy when on main
